=== cosminbucur/upskill/json-schema/src/main/resources/schema/ComplexSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$schemaId": "sda.v1.ComplexSchema",
  "$owner": "user@sda.com",
  "title": "Parent state",
  "description": "Contains most important schema objects.",
  "type": "object",
  "required": [
    "id",
    "lastUpdated",
    "name",
    "childObject"
  ],
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64",
      "description": "object id"
    },
    "lastUpdated": {
      "type": "string",
      "format": "date-time",
      "description": "timestamp with timezone"
    },
    "name": {
      "type": "string",
      "description": "parent name"
    },
    "childObject": {
      "$ref": "ChildObject.json"
    }
  }
}

=== cosminbucur/upskill/json-schema/src/main/resources/json/valid.json
{
  "id": 123,
  "lastUpdated": "2019-12-21T06:26:51.933015Z",
  "name": "invitation",
  "childObject": {
    "clock": {
      "status": "ACTIVE",
      "clockRunning": true
    },
    "events": [
      {
        "location": "Romania",
        "time": {
          "minutes": 10,
          "seconds": 30
        }
      },
      {
        "location": "Germany",
        "time": {
          "minutes": 5,
          "seconds": 15
        }
      }
    ]
  }
}
